### ISSUE TITLE
Extended stats.

### ISSUE THREAD

**Issue by FuriousZahn** [Repooc/ElvUI_CataArmory#18]
Not really an issue, just a suggestion. 
What do you think of using a bit more of the empty space in the side panel? 
Maybe give us the option to add/remove stats and have it a bit more like Extended Character Stats addon if we want to?

Beautiful ElvUI plugin, by the way. Love it so much.

**Comment by seathasky** [comment]
I think he is working on a fix for this. I have the same issue with gearquipper being covered up by the side panel

**Comment by Repooc** [comment]
i have a couple different ideas atm but have not started working on it just yet as irl jobs (yes multiple jobs) have made my ass tired as hell when i get home lol

**Comment by seathasky** [comment]
> i have a couple different ideas atm but have not started working on it just yet as irl jobs (yes multiple jobs) have made my ass tired as hell when i get home lol

What about just making it so that other addons can overlay that section?

**Comment by FuriousZahn** [comment]
How about adding Gear Score under the Item Level?

**Comment by seathasky** [comment]
Gearscore is extremely redundant as we already have ilvl in game. People trying to bring back an outdated method of checking gear makes no sense.

**Comment by FuriousZahn** [comment]
I agree with you and I hate it, but PuGs keep asking for it.

**Comment by seathasky** [comment]
> I agree with you and I hate it, but PuGs keep asking for it.

Was gearscore ever used past Wrath? I can't remember.

**Comment by linkx2252** [comment]
+1 for gearscore. I agree its stupid, but pugs will ask and we have to play their stupid game. Would love an option to add it in.
