### ISSUE TITLE
Hunter Hit Rating

### ISSUE THREAD

**Issue by gsnehme92** [Repooc/ElvUI_CataArmory#34]
Are you able to incorporate Hunter's Hit Talent Focused Aim to appear in the Hit Rating section? It would be a quality of life update to include these stats.

Currently it only provides you data on your hit rating without the MarksMan talents.

**Comment by Repooc** [comment]
closing this as its old, if u still need something specific, just make a new ticket as I am redoing this for cata and some stuff is different...
