### ISSUE TITLE
Warning Indicator for rings

### ISSUE THREAD

**Issue by Astraar** [Repooc/ElvUI_CataArmory#39]
The Warning Indicator is shown for rings even though im not an enchanter.

![M5HtnUx](https://github.com/Repooc/ElvUI_CataArmory/assets/925489/56a91496-4308-41f1-8bc9-b7b6512b9468)

**Comment by Repooc** [comment]
this wont work correctly for inspect frame at all as I have not account for this... the inspect frame will never show warning for missing enchant once i go over the code for it as we are not able to get their prof info reliably... test out the latest alpha to see if it goes away for your character frame on toons without enchanting, and if u have toons with enchanting, it would be nice to ensure it works for them as well

**Comment by Astraar** [comment]
on login it does not work, after reload it did. tested it with and without enchanting

i added some print in the profession check for science and it did not fire off on login

**Comment by Repooc** [comment]
can you screen record what you are doing?

**Comment by Repooc** [comment]
If you have discord, sometimes real time chat is faster as well... The discord link is in the addon description (or at least should be).  I have something i think you may have better luck with... try the new commit, which should hit clients soonish

**Comment by Astraar** [comment]
works now on login and reload. thanks!

**Comment by Repooc** [comment]
> works now on login and reload. thanks!

Sounds good
