### ISSUE TITLE
Missing enchant ids 4190, 4439

### ISSUE THREAD

**Issue by dl0802** [Repooc/ElvUI_CataArmory#40]
Missing the following enchant ids:
Spell id 4190 (145 stam + 55 agi, self leatherworking emboss) not showing up on legs
Spell id 4439 (130 agi, self leatherworking emboss) not showing up on bracers

Here are the messages I get when I open my character pane:

![Screenshot 2024-05-24 215537](https://github.com/Repooc/ElvUI_CataArmory/assets/46177909/d9ea8a6b-f7d4-4e47-8f57-20588b39d5d7)

Here are the hover screenshots of my items:
![Screenshot 2024-05-24 215600](https://github.com/Repooc/ElvUI_CataArmory/assets/46177909/86395cf2-d550-4b1b-bc88-297b3ae24fb1)
![Screenshot 2024-05-24 215625](https://github.com/Repooc/ElvUI_CataArmory/assets/46177909/1736eec1-bb82-4bcb-9234-16ecc0bb6613)

**Comment by Repooc** [comment]
Hmm I am glad I asked for the images because it appears it is 4190 for +130 Agi, then the 4439 is the +145 stam & 55 agi as your message appears backwards lol

**Comment by Repooc** [comment]
btw I added tooltip info that shows enchant id on items with enchants, will add options for it when i get back home from work.
