### ISSUE TITLE
LW Enchants not recognized

### ISSUE THREAD

**Issue by cyR1c** [Repooc/ElvUI_CataArmory#42]
The LW enchants are not recognized ingame

https://www.wowhead.com/cata/spell=85007/draconic-embossment-stamina
https://www.wowhead.com/cata/spell=101600/drakehide-leg-reinforcements

Those 2 are not working, I did not test the other 5 but i guess it would be the same

![image](https://github.com/Repooc/ElvUI_CataArmory/assets/24959801/0bcc247d-c1cf-4694-a2fb-2e4e03c4aafd)

**Comment by Repooc** [comment]
can u get me a picture of the 2nd item where the enchant id is showing so i can add it
and for the others you believe are missing, i will need enchant id info for those as well... that is the prob with how we have to get enchant info... we get enchant ids but cant really get the text with it

**Comment by Repooc** [comment]
![image](https://github.com/Repooc/ElvUI_CataArmory/assets/1479745/4e44b568-b0b0-45be-816b-17f2c870e10a)
not sure but this may be the enchant id, but if u can verify that, i would appreciate it

**Comment by Repooc** [comment]
pushed it just in case it is right, just let me know either way if you can

**Comment by cyR1c** [comment]
The 4 I am using now work. Thank you!
