### ISSUE TITLE
Tailoring enchant missing

### ISSUE THREAD

**Issue by seakoria** [Repooc/ElvUI_CataArmory#43]
Cata Armory 1.11: The enchant id, 4115, seems to be missing from our database
It's a tailoring enchant.

**Comment by Repooc** [comment]
Assuming you are using the alpha build I need the info it says. Screenshot of you missing over the item so I can get the enchant text and id in one image as tech the message wants an image of chat as well, it's not needed since I added the id to the item id the option is enabled

**Comment by seakoria** [comment]
You fixed it already,thank you very much, sir!

**Comment by Repooc** [comment]
sweet yw
