### ISSUE TITLE
Suggestion: Abbreviated enchanting text

### ISSUE THREAD

**Issue by Ghaan** [Repooc/ElvUI_CataArmory#45]
Just found this plugin for Elv and just love it tbh.

Only thing I found wanting with it is the ability to set the length of the enchanting text or just abbreviating some of it.
Like shoulder enchant of "+40 Attack Power & +15 Crit" can be cut down to just "+40 AP & +15 Crit".

Examples of what it could be cut down to, to clarify what I meant.
![Skärmbild 2024-06-07 140643](https://github.com/Repooc/ElvUI_CataArmory/assets/41453013/a19f1f45-85df-42f9-98e3-a256c2dcd48a)
Helm "+60 Int & +35 Crit"
Shoulders "+50 Int & +25 Haste"
Cloak "Lightweave"
Chest "+15 Stats"
Wrist "+50 Crit"
Gloves "+50 Haste"
Legs "+95 Int & +80 Stam"
Boots "+50 Haste"
OH "+40 Int"

If this is even something you'd be willing/have time to work on.
If not, where could I look into in order to do this on my own?

**Comment by Ghaan** [comment]
And to add, since I saw you answered this questions a few times before, issue with overlapping still exists in some cases. So if the option to abbreviate to all the "Str/Agi/Int/Stam/AP/SP" etc etc would be absolutely golden.

Example:
![bild](https://github.com/Repooc/ElvUI_CataArmory/assets/41453013/56689026-1280-449b-b499-94d00d498616)

**Comment by hoaraucg** [comment]
This option already exists in the current version. First you'd like want to start using the new "EnchantID Tooltip Info" option under Enchants in Character and Inspect. This will add the EnchantID to the tooltip of the item that you'd like to change the name on.

Then in the Enchant Strings options Tab, enter that EnchantID, and what you would prefer the enchant be renamed to.

**Comment by Ghaan** [comment]
![Skärmbild 2024-06-07 160807](https://github.com/Repooc/ElvUI_CataArmory/assets/41453013/8f08cd12-1a32-47dc-b3cb-6042b1eb336c)

Actually figured out how to do it on my own. Not sure if it helps incorporating it as a toggle-able option for the plugin for you Repooc, don't know coding that in-depth. But happy to help if it does.

If anyone else want to have it look like this. Grab the attached file and replace the "LibGetEnchantDB.lua" file found in "\World of Warcraft\_classic_\Interface\AddOns\ElvUI_CataArmory\Libs\LibGetEnchant-1.0". Make sure you rename the filed in the .zip and remove the "_ABBREVIATED" at the end.

I recommend you make a backup of the original "LibGetEnchantDB.lua" file if you want to revert to default, just add "_BACKUP" behind the .lua extension.

[LibGetEnchantDB.zip](https://github.com/user-attachments/files/15740919/LibGetEnchantDB.zip)

**Comment by Ghaan** [comment]
> This option already exists in the current version. First you'd like want to start using the new "EnchantID Tooltip Info" option under Enchants in Character and Inspect. This will add the EnchantID to the tooltip of the item that you'd like to change the name on.
> 
> Then in the Enchant Strings options Tab, enter that EnchantID, and what you would prefer the enchant be renamed to.

Had totally missed that, thank you. 
But was mostly after a blanket "overhaul" so you wouldn't need to do it manually for each enchant. 

I did however figured out how to change the it with Notepad++. I'm not knowledgeable in coding at all, so use it at your own risk as I don't know if it fudges any other things with the plugin. I personally haven't had any errors so far at least using it.

![Skärmbild 2024-06-07 160807](https://github.com/Repooc/ElvUI_CataArmory/assets/41453013/8f08cd12-1a32-47dc-b3cb-6042b1eb336c)
So if anyone else stumbles across this and want to have it look like this above image. Grab the attached file and replace the "LibGetEnchantDB.lua" file found in "\World of Warcraft\_classic_\Interface\AddOns\ElvUI_CataArmory\Libs\LibGetEnchant-1.0". Make sure you rename the filed in the .zip and remove the "_ABBREVIATED" at the end.

I recommend you make a backup of the original "LibGetEnchantDB.lua" file if you want to revert to default, just add "_BACKUP" behind the .lua extension.

[LibGetEnchantDB.zip](https://github.com/user-attachments/files/15740919/LibGetEnchantDB.zip)

**Comment by Repooc** [comment]
Do Not do what has been recommended by the users to edit the file. This is not recommended or supported as the addon has a built in way to shorten the strings.

**Comment by Repooc** [comment]
Also heads up, there is another rewrite in progress to address some things people had requested which will require settings to redone but after typing that... I will try to keep the text replacement entries users do in the current version.
