### ISSUE TITLE
Collapsible side-bar

### ISSUE THREAD

**Issue by Raulfin** [Repooc/ElvUI_CataArmory#8]
Can you make the side-bar collapsible? There are several other addons that use that same space like Extended Character Stats, and Outfitter, but they both use a lower layer by default and become hidden under WrathArmory when opened.

![WowClassic_bAx8ScqGOY](https://user-images.githubusercontent.com/7994405/194209167-24864b0c-1019-4e30-880b-93a751478e48.png)

**Comment by Repooc** [comment]
not out of the question as i have some comment out stuff for a button for it locally just havent worked on anything yet
